### ISSUE TITLE
Look into the parallelization techniques in TC2024

### ISSUE THREAD

**Issue by eth1030** [md-hpc/cuda#1]

**Comment by eth1030** [comment]
https://docs.google.com/document/d/1OczmmPxIOq5KVLq1kMmW-euP22yLyEgJ7VTcS6vvs_M/edit?usp=sharing

**Comment by ajamias** [comment]
We will be using algorithm 3 in the paper. Each thread block will be assigned a home_cell-neighbor_cell pair, and each thread in a thread block will be assigned a reference particle in the home cell and loop over each particle in the neighbor cell and calculate the acceleration/force.
